// Comprehensive Nigerian wholesale drink product library
// Each entry represents a specific product variant with its pack size

export interface LibraryProduct {
  name: string;        // e.g. "Fanta Orange 35cl"
  brand: string;       // e.g. "Fanta"
  category: string;
  packSize: string;    // e.g. "Crate (24 bottles)"
}

export const productLibrary: LibraryProduct[] = [
  // ─── COCA-COLA FAMILY ──────────────────────────────────────
  { name: 'Coca-Cola 35cl', brand: 'Coca-Cola', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Coca-Cola 50cl', brand: 'Coca-Cola', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: 'Coca-Cola 60cl PET', brand: 'Coca-Cola', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: 'Coca-Cola 1L PET', brand: 'Coca-Cola', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: 'Coca-Cola 1.5L PET', brand: 'Coca-Cola', category: 'Soft Drink', packSize: 'Pack (8 bottles)' },
  { name: 'Coca-Cola 33cl Can', brand: 'Coca-Cola', category: 'Soft Drink', packSize: 'Pack (24 cans)' },
  { name: 'Coca-Cola Zero 35cl', brand: 'Coca-Cola', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Coca-Cola Zero 50cl Can', brand: 'Coca-Cola', category: 'Soft Drink', packSize: 'Pack (24 cans)' },

  // ─── FANTA ─────────────────────────────────────────────────
  { name: 'Fanta Orange 35cl', brand: 'Fanta', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Fanta Orange 50cl', brand: 'Fanta', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: 'Fanta Orange 60cl PET', brand: 'Fanta', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: 'Fanta Orange 1L PET', brand: 'Fanta', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: 'Fanta Orange 1.5L PET', brand: 'Fanta', category: 'Soft Drink', packSize: 'Pack (8 bottles)' },
  { name: 'Fanta Lemon 35cl', brand: 'Fanta', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Fanta Chapman 35cl', brand: 'Fanta', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Fanta Blackcurrant 35cl', brand: 'Fanta', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Fanta Apple 35cl', brand: 'Fanta', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Fanta Pineapple 35cl', brand: 'Fanta', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },

  // ─── SPRITE ────────────────────────────────────────────────
  { name: 'Sprite 35cl', brand: 'Sprite', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Sprite 50cl', brand: 'Sprite', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: 'Sprite 60cl PET', brand: 'Sprite', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: 'Sprite 1.5L PET', brand: 'Sprite', category: 'Soft Drink', packSize: 'Pack (8 bottles)' },
  { name: 'Sprite 33cl Can', brand: 'Sprite', category: 'Soft Drink', packSize: 'Pack (24 cans)' },

  // ─── PEPSI / 7UP / MIRINDA ─────────────────────────────────
  { name: 'Pepsi 35cl', brand: 'Pepsi', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Pepsi 50cl', brand: 'Pepsi', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: 'Pepsi 60cl PET', brand: 'Pepsi', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: 'Pepsi 33cl Can', brand: 'Pepsi', category: 'Soft Drink', packSize: 'Pack (24 cans)' },
  { name: '7Up 35cl', brand: '7Up', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: '7Up 50cl', brand: '7Up', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: '7Up 60cl PET', brand: '7Up', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: '7Up 33cl Can', brand: '7Up', category: 'Soft Drink', packSize: 'Pack (24 cans)' },
  { name: 'Mirinda Orange 35cl', brand: 'Mirinda', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Mirinda Orange 50cl', brand: 'Mirinda', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: 'Mirinda Apple 35cl', brand: 'Mirinda', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Mountain Dew 35cl', brand: 'Mountain Dew', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Mountain Dew 50cl PET', brand: 'Mountain Dew', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: 'Teem Bitter Lemon 35cl', brand: 'Teem', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Teem Soda Water 35cl', brand: 'Teem', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Schweppes Tonic Water 35cl', brand: 'Schweppes', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Schweppes Soda Water 35cl', brand: 'Schweppes', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Schweppes Chapman 33cl Can', brand: 'Schweppes', category: 'Soft Drink', packSize: 'Pack (24 cans)' },
  { name: 'Limca 35cl', brand: 'Limca', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Krest Bitter Lemon 35cl', brand: 'Krest', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'Crush Orange 35cl', brand: 'Crush', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },
  { name: 'RC Cola 35cl', brand: 'RC Cola', category: 'Soft Drink', packSize: 'Crate (24 bottles)' },

  // ─── BEER ──────────────────────────────────────────────────
  { name: 'Star Lager 60cl', brand: 'Star', category: 'Beer', packSize: 'Crate (12 bottles)' },
  { name: 'Star Lager 33cl', brand: 'Star', category: 'Beer', packSize: 'Crate (24 bottles)' },
  { name: 'Star Lager 50cl Can', brand: 'Star', category: 'Beer', packSize: 'Pack (24 cans)' },
  { name: 'Star Radler Lemon 33cl', brand: 'Star', category: 'Beer', packSize: 'Pack (24 bottles)' },
  { name: 'Star Radler Grapefruit 33cl', brand: 'Star', category: 'Beer', packSize: 'Pack (24 bottles)' },
  { name: 'Gulder Lager 60cl', brand: 'Gulder', category: 'Beer', packSize: 'Crate (12 bottles)' },
  { name: 'Gulder Lager 33cl', brand: 'Gulder', category: 'Beer', packSize: 'Crate (24 bottles)' },
  { name: 'Gulder Lager 50cl Can', brand: 'Gulder', category: 'Beer', packSize: 'Pack (24 cans)' },
  { name: 'Trophy Lager 60cl', brand: 'Trophy', category: 'Beer', packSize: 'Crate (12 bottles)' },
  { name: 'Trophy Lager 33cl', brand: 'Trophy', category: 'Beer', packSize: 'Crate (24 bottles)' },
  { name: 'Heineken 33cl', brand: 'Heineken', category: 'Beer', packSize: 'Pack (6 bottles)' },
  { name: 'Heineken 50cl Can', brand: 'Heineken', category: 'Beer', packSize: 'Pack (24 cans)' },
  { name: 'Heineken 33cl Can', brand: 'Heineken', category: 'Beer', packSize: 'Pack (24 cans)' },
  { name: 'Budweiser 33cl Can', brand: 'Budweiser', category: 'Beer', packSize: 'Pack (6 cans)' },
  { name: 'Budweiser 50cl Can', brand: 'Budweiser', category: 'Beer', packSize: 'Pack (24 cans)' },
  { name: 'Life Lager 60cl', brand: 'Life', category: 'Beer', packSize: 'Crate (12 bottles)' },
  { name: 'Life Lager 33cl', brand: 'Life', category: 'Beer', packSize: 'Crate (24 bottles)' },
  { name: '33 Export Lager 60cl', brand: '33 Export', category: 'Beer', packSize: 'Crate (12 bottles)' },
  { name: '33 Export Lager 33cl', brand: '33 Export', category: 'Beer', packSize: 'Crate (24 bottles)' },
  { name: 'Hero Lager 60cl', brand: 'Hero', category: 'Beer', packSize: 'Crate (12 bottles)' },
  { name: 'Hero Lager 33cl', brand: 'Hero', category: 'Beer', packSize: 'Crate (24 bottles)' },
  { name: 'Goldberg Lager 60cl', brand: 'Goldberg', category: 'Beer', packSize: 'Crate (12 bottles)' },
  { name: 'Goldberg Lager 33cl', brand: 'Goldberg', category: 'Beer', packSize: 'Crate (24 bottles)' },
  { name: 'Tiger Lager 50cl Can', brand: 'Tiger', category: 'Beer', packSize: 'Pack (24 cans)' },
  { name: 'Tiger Lager 33cl', brand: 'Tiger', category: 'Beer', packSize: 'Pack (24 bottles)' },
  { name: 'Harp Lager 60cl', brand: 'Harp', category: 'Beer', packSize: 'Crate (12 bottles)' },
  { name: 'Harp Lager 33cl', brand: 'Harp', category: 'Beer', packSize: 'Crate (24 bottles)' },
  { name: 'Eagle Lager 60cl', brand: 'Eagle', category: 'Beer', packSize: 'Crate (12 bottles)' },
  { name: 'Eagle Lager 33cl', brand: 'Eagle', category: 'Beer', packSize: 'Crate (24 bottles)' },
  { name: 'Castle Lager 33cl Can', brand: 'Castle', category: 'Beer', packSize: 'Pack (24 cans)' },
  { name: 'Desperados 33cl', brand: 'Desperados', category: 'Beer', packSize: 'Pack (24 bottles)' },
  { name: 'Beck\'s Ice 27.5cl', brand: 'Beck\'s', category: 'Beer', packSize: 'Pack (24 bottles)' },
  { name: 'Turbo King 60cl', brand: 'Turbo King', category: 'Beer', packSize: 'Crate (12 bottles)' },
  { name: 'Legend Lager 60cl', brand: 'Legend', category: 'Beer', packSize: 'Crate (12 bottles)' },
  { name: 'Williams Dark Ale 33cl', brand: 'Williams', category: 'Beer', packSize: 'Pack (24 bottles)' },
  { name: 'More Lager 60cl', brand: 'More', category: 'Beer', packSize: 'Crate (12 bottles)' },

  // ─── STOUT ─────────────────────────────────────────────────
  { name: 'Guinness FES 60cl', brand: 'Guinness', category: 'Stout', packSize: 'Crate (12 bottles)' },
  { name: 'Guinness FES 33cl', brand: 'Guinness', category: 'Stout', packSize: 'Crate (24 bottles)' },
  { name: 'Guinness Smooth 50cl Can', brand: 'Guinness', category: 'Stout', packSize: 'Pack (24 cans)' },
  { name: 'Guinness Smooth 33cl Can', brand: 'Guinness', category: 'Stout', packSize: 'Pack (24 cans)' },
  { name: 'Guinness Gold 33cl', brand: 'Guinness', category: 'Stout', packSize: 'Pack (24 bottles)' },
  { name: 'Legend Extra Stout 60cl', brand: 'Legend', category: 'Stout', packSize: 'Crate (12 bottles)' },
  { name: 'Legend Extra Stout 33cl', brand: 'Legend', category: 'Stout', packSize: 'Crate (24 bottles)' },
  { name: 'Orijin 60cl', brand: 'Orijin', category: 'Stout', packSize: 'Crate (12 bottles)' },
  { name: 'Orijin 33cl', brand: 'Orijin', category: 'Stout', packSize: 'Crate (24 bottles)' },
  { name: 'Trophy Stout 60cl', brand: 'Trophy', category: 'Stout', packSize: 'Crate (12 bottles)' },
  { name: 'Trophy Stout 30cl Can', brand: 'Trophy', category: 'Stout', packSize: 'Pack (24 cans)' },
  { name: 'Star Extra Stout 60cl', brand: 'Star', category: 'Stout', packSize: 'Crate (12 bottles)' },
  { name: 'Satzenbrau Stout 50cl Can', brand: 'Satzenbrau', category: 'Stout', packSize: 'Pack (24 cans)' },

  // ─── MALT DRINKS ───────────────────────────────────────────
  { name: 'Maltina 33cl', brand: 'Maltina', category: 'Malt', packSize: 'Pack (24 bottles)' },
  { name: 'Maltina 50cl PET', brand: 'Maltina', category: 'Malt', packSize: 'Pack (12 bottles)' },
  { name: 'Maltina Can 33cl', brand: 'Maltina', category: 'Malt', packSize: 'Pack (24 cans)' },
  { name: 'Maltina Strawberry 33cl', brand: 'Maltina', category: 'Malt', packSize: 'Pack (24 bottles)' },
  { name: 'Maltina Pineapple 33cl', brand: 'Maltina', category: 'Malt', packSize: 'Pack (24 bottles)' },
  { name: 'Amstel Malta 33cl', brand: 'Amstel Malta', category: 'Malt', packSize: 'Pack (24 bottles)' },
  { name: 'Amstel Malta 50cl PET', brand: 'Amstel Malta', category: 'Malt', packSize: 'Pack (12 bottles)' },
  { name: 'Amstel Malta Can 33cl', brand: 'Amstel Malta', category: 'Malt', packSize: 'Pack (24 cans)' },
  { name: 'Hi-Malt 33cl', brand: 'Hi-Malt', category: 'Malt', packSize: 'Pack (24 bottles)' },
  { name: 'Hi-Malt 50cl PET', brand: 'Hi-Malt', category: 'Malt', packSize: 'Pack (12 bottles)' },
  { name: 'Dubic Malt 33cl', brand: 'Dubic', category: 'Malt', packSize: 'Pack (24 bottles)' },
  { name: 'Beta Malt 33cl', brand: 'Beta Malt', category: 'Malt', packSize: 'Pack (24 bottles)' },
  { name: 'Grand Malt 33cl', brand: 'Grand Malt', category: 'Malt', packSize: 'Pack (24 bottles)' },
  { name: 'Grand Malt 50cl PET', brand: 'Grand Malt', category: 'Malt', packSize: 'Pack (12 bottles)' },
  { name: 'Malta Guinness 33cl', brand: 'Malta Guinness', category: 'Malt', packSize: 'Pack (24 bottles)' },
  { name: 'Malta Guinness 50cl PET', brand: 'Malta Guinness', category: 'Malt', packSize: 'Pack (12 bottles)' },
  { name: 'Malta Guinness Can 33cl', brand: 'Malta Guinness', category: 'Malt', packSize: 'Pack (24 cans)' },
  { name: 'Vitamalt 33cl', brand: 'Vitamalt', category: 'Malt', packSize: 'Pack (24 bottles)' },
  { name: 'Vitamalt Plus 33cl', brand: 'Vitamalt', category: 'Malt', packSize: 'Pack (24 bottles)' },

  // ─── ENERGY DRINKS ─────────────────────────────────────────
  { name: 'Fearless Energy 33cl Can', brand: 'Fearless', category: 'Energy', packSize: 'Pack (24 cans)' },
  { name: 'Fearless Red Berry 33cl Can', brand: 'Fearless', category: 'Energy', packSize: 'Pack (24 cans)' },
  { name: 'Fearless Citrus 33cl Can', brand: 'Fearless', category: 'Energy', packSize: 'Pack (24 cans)' },
  { name: 'Power Horse 25cl Can', brand: 'Power Horse', category: 'Energy', packSize: 'Pack (24 cans)' },
  { name: 'Power Horse 50cl Can', brand: 'Power Horse', category: 'Energy', packSize: 'Pack (24 cans)' },
  { name: 'Bullet Energy 33cl Can', brand: 'Bullet', category: 'Energy', packSize: 'Pack (24 cans)' },
  { name: 'Bullet Energy 50cl Can', brand: 'Bullet', category: 'Energy', packSize: 'Pack (24 cans)' },
  { name: 'Predator Energy 25cl Can', brand: 'Predator', category: 'Energy', packSize: 'Pack (24 cans)' },
  { name: 'Predator Energy 50cl Can', brand: 'Predator', category: 'Energy', packSize: 'Pack (24 cans)' },
  { name: 'Climax Energy 33cl Can', brand: 'Climax', category: 'Energy', packSize: 'Pack (24 cans)' },
  { name: 'Climax Energy 50cl PET', brand: 'Climax', category: 'Energy', packSize: 'Pack (12 bottles)' },
  { name: 'Red Bull 25cl Can', brand: 'Red Bull', category: 'Energy', packSize: 'Pack (24 cans)' },
  { name: 'Red Bull Sugar Free 25cl Can', brand: 'Red Bull', category: 'Energy', packSize: 'Pack (24 cans)' },
  { name: 'Monster Energy 50cl Can', brand: 'Monster', category: 'Energy', packSize: 'Pack (12 cans)' },
  { name: 'Monster Ultra 50cl Can', brand: 'Monster', category: 'Energy', packSize: 'Pack (12 cans)' },
  { name: 'Viju Power 35cl', brand: 'Viju', category: 'Energy', packSize: 'Pack (24 bottles)' },
  { name: 'Sting Energy 33cl Can', brand: 'Sting', category: 'Energy', packSize: 'Pack (24 cans)' },
  { name: 'Lucozade Boost 33cl', brand: 'Lucozade', category: 'Energy', packSize: 'Pack (24 bottles)' },
  { name: 'Lucozade Boost 50cl PET', brand: 'Lucozade', category: 'Energy', packSize: 'Pack (12 bottles)' },
  { name: 'Lucozade Sport 50cl PET', brand: 'Lucozade', category: 'Energy', packSize: 'Pack (12 bottles)' },
  { name: 'Dragon Energy 33cl Can', brand: 'Dragon', category: 'Energy', packSize: 'Pack (24 cans)' },

  // ─── WATER ─────────────────────────────────────────────────
  { name: 'Eva Water 75cl', brand: 'Eva', category: 'Water', packSize: 'Pack (12 bottles)' },
  { name: 'Eva Water 1.5L', brand: 'Eva', category: 'Water', packSize: 'Pack (12 bottles)' },
  { name: 'Eva Water 50cl', brand: 'Eva', category: 'Water', packSize: 'Pack (20 bottles)' },
  { name: 'Aquafina 50cl', brand: 'Aquafina', category: 'Water', packSize: 'Pack (20 bottles)' },
  { name: 'Aquafina 75cl', brand: 'Aquafina', category: 'Water', packSize: 'Pack (12 bottles)' },
  { name: 'Aquafina 1.5L', brand: 'Aquafina', category: 'Water', packSize: 'Pack (12 bottles)' },
  { name: 'Nestle Pure Life 50cl', brand: 'Nestle', category: 'Water', packSize: 'Pack (20 bottles)' },
  { name: 'Nestle Pure Life 75cl', brand: 'Nestle', category: 'Water', packSize: 'Pack (12 bottles)' },
  { name: 'Nestle Pure Life 1.5L', brand: 'Nestle', category: 'Water', packSize: 'Pack (12 bottles)' },
  { name: 'Cway Water 50cl', brand: 'Cway', category: 'Water', packSize: 'Pack (20 bottles)' },
  { name: 'Cway Water 75cl', brand: 'Cway', category: 'Water', packSize: 'Pack (12 bottles)' },
  { name: 'Cway Water 1.5L', brand: 'Cway', category: 'Water', packSize: 'Pack (12 bottles)' },
  { name: 'Ragolis Water 50cl', brand: 'Ragolis', category: 'Water', packSize: 'Pack (20 bottles)' },
  { name: 'Ragolis Water 75cl', brand: 'Ragolis', category: 'Water', packSize: 'Pack (12 bottles)' },
  { name: 'Ragolis Water 1.5L', brand: 'Ragolis', category: 'Water', packSize: 'Pack (12 bottles)' },
  { name: 'Swan Water 50cl', brand: 'Swan', category: 'Water', packSize: 'Pack (20 bottles)' },
  { name: 'Swan Water 75cl', brand: 'Swan', category: 'Water', packSize: 'Pack (12 bottles)' },
  { name: 'Gossy Water 50cl', brand: 'Gossy', category: 'Water', packSize: 'Pack (20 bottles)' },

  // ─── JUICE / YOGHURT ──────────────────────────────────────
  { name: 'Five Alive Pulpy Orange 35cl', brand: 'Five Alive', category: 'Juice', packSize: 'Pack (24 cartons)' },
  { name: 'Five Alive Pulpy Orange 1L', brand: 'Five Alive', category: 'Juice', packSize: 'Pack (12 cartons)' },
  { name: 'Five Alive Citrus Burst 35cl', brand: 'Five Alive', category: 'Juice', packSize: 'Pack (24 cartons)' },
  { name: 'Five Alive Berry Blast 35cl', brand: 'Five Alive', category: 'Juice', packSize: 'Pack (24 cartons)' },
  { name: 'Chi Exotic 1L', brand: 'Chi Exotic', category: 'Juice', packSize: 'Pack (12 cartons)' },
  { name: 'Chi Exotic 35cl', brand: 'Chi Exotic', category: 'Juice', packSize: 'Pack (24 cartons)' },
  { name: 'Chi Happy Hour 35cl', brand: 'Chi', category: 'Juice', packSize: 'Pack (24 cartons)' },
  { name: 'Chi Active 35cl', brand: 'Chi', category: 'Juice', packSize: 'Pack (24 cartons)' },
  { name: 'Hollandia Yoghurt 50cl', brand: 'Hollandia', category: 'Juice', packSize: 'Pack (12 bottles)' },
  { name: 'Hollandia Yoghurt 1L', brand: 'Hollandia', category: 'Juice', packSize: 'Pack (12 bottles)' },
  { name: 'Hollandia Yoghurt 31.5cl', brand: 'Hollandia', category: 'Juice', packSize: 'Pack (24 bottles)' },
  { name: 'Cway Juice 1L', brand: 'Cway', category: 'Juice', packSize: 'Pack (12 cartons)' },
  { name: 'Chivita 100% Orange 1L', brand: 'Chivita', category: 'Juice', packSize: 'Pack (12 cartons)' },
  { name: 'Chivita 100% Apple 1L', brand: 'Chivita', category: 'Juice', packSize: 'Pack (12 cartons)' },
  { name: 'Chivita Active 1L', brand: 'Chivita', category: 'Juice', packSize: 'Pack (12 cartons)' },
  { name: 'Chivita Ice Tea 35cl', brand: 'Chivita', category: 'Juice', packSize: 'Pack (24 cartons)' },
  { name: 'Viju Milk 50cl', brand: 'Viju', category: 'Juice', packSize: 'Pack (12 bottles)' },
  { name: 'Viju Chocolate 50cl', brand: 'Viju', category: 'Juice', packSize: 'Pack (12 bottles)' },
  { name: 'Viju Apple 35cl', brand: 'Viju', category: 'Juice', packSize: 'Pack (24 bottles)' },
  { name: 'Ribena 35cl', brand: 'Ribena', category: 'Juice', packSize: 'Pack (24 cartons)' },
  { name: 'Ribena 1L', brand: 'Ribena', category: 'Juice', packSize: 'Pack (12 cartons)' },
  { name: 'Capri-Sun 20cl', brand: 'Capri-Sun', category: 'Juice', packSize: 'Pack (40 pouches)' },
  { name: 'Bigi Apple 35cl PET', brand: 'Bigi', category: 'Juice', packSize: 'Pack (24 bottles)' },
  { name: 'Bigi Orange 35cl PET', brand: 'Bigi', category: 'Juice', packSize: 'Pack (24 bottles)' },
  { name: 'Bigi Tropical 35cl PET', brand: 'Bigi', category: 'Juice', packSize: 'Pack (24 bottles)' },
  { name: 'Bigi Chapman 35cl PET', brand: 'Bigi', category: 'Juice', packSize: 'Pack (24 bottles)' },
  { name: 'Bigi Cola 35cl PET', brand: 'Bigi', category: 'Soft Drink', packSize: 'Pack (24 bottles)' },
  { name: 'Bigi Cola 60cl PET', brand: 'Bigi', category: 'Soft Drink', packSize: 'Pack (12 bottles)' },
  { name: 'Bigi Lemon & Lime 35cl PET', brand: 'Bigi', category: 'Soft Drink', packSize: 'Pack (24 bottles)' },

  // ─── WINE / SPIRIT / RTD ──────────────────────────────────
  { name: 'Smirnoff Ice 33cl', brand: 'Smirnoff', category: 'Spirit', packSize: 'Pack (24 bottles)' },
  { name: 'Smirnoff Ice Double Black 33cl', brand: 'Smirnoff', category: 'Spirit', packSize: 'Pack (24 bottles)' },
  { name: 'Smirnoff Vodka 75cl', brand: 'Smirnoff', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Smirnoff Vodka 1L', brand: 'Smirnoff', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Small Stout 20cl', brand: 'Small Stout', category: 'Spirit', packSize: 'Carton (24 bottles)' },
  { name: 'Origin Zero 25cl', brand: 'Origin', category: 'Spirit', packSize: 'Carton (24 bottles)' },
  { name: 'Orijin Bitters 60cl', brand: 'Orijin', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Orijin Bitters 75cl', brand: 'Orijin', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Orijin Ready-to-Drink 33cl', brand: 'Orijin', category: 'Spirit', packSize: 'Pack (24 bottles)' },
  { name: 'Gordon\'s Spark Lime 33cl', brand: 'Gordon\'s', category: 'Spirit', packSize: 'Pack (24 bottles)' },
  { name: 'Gordon\'s Spark Ginger 33cl', brand: 'Gordon\'s', category: 'Spirit', packSize: 'Pack (24 bottles)' },
  { name: 'Gordon\'s Dry Gin 75cl', brand: 'Gordon\'s', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Gordon\'s Dry Gin 1L', brand: 'Gordon\'s', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Hennessy VS 70cl', brand: 'Hennessy', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Hennessy VSOP 70cl', brand: 'Hennessy', category: 'Spirit', packSize: 'Carton (6 bottles)' },
  { name: 'Baileys Irish Cream 75cl', brand: 'Baileys', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Baileys Irish Cream 1L', brand: 'Baileys', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Johnnie Walker Red 75cl', brand: 'Johnnie Walker', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Johnnie Walker Black 75cl', brand: 'Johnnie Walker', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Captain Morgan 75cl', brand: 'Captain Morgan', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Jack Daniel\'s 70cl', brand: 'Jack Daniel\'s', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Martini Rosso 75cl', brand: 'Martini', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Martini Bianco 75cl', brand: 'Martini', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'André Sparkling Wine 75cl', brand: 'André', category: 'Wine', packSize: 'Carton (12 bottles)' },
  { name: 'Four Cousins Sweet Red 75cl', brand: 'Four Cousins', category: 'Wine', packSize: 'Carton (12 bottles)' },
  { name: 'Four Cousins Sweet White 75cl', brand: 'Four Cousins', category: 'Wine', packSize: 'Carton (12 bottles)' },
  { name: 'Drostdy-Hof Sweet Rose 75cl', brand: 'Drostdy-Hof', category: 'Wine', packSize: 'Carton (12 bottles)' },
  { name: 'Don Simon Tempranillo 1L', brand: 'Don Simon', category: 'Wine', packSize: 'Carton (12 cartons)' },
  { name: 'Carlo Rossi California Red 75cl', brand: 'Carlo Rossi', category: 'Wine', packSize: 'Carton (6 bottles)' },
  { name: 'Moet & Chandon Brut 75cl', brand: 'Moet', category: 'Wine', packSize: 'Carton (6 bottles)' },
  { name: 'Baron De Lestac Bordeaux 75cl', brand: 'Baron De Lestac', category: 'Wine', packSize: 'Carton (6 bottles)' },
  { name: 'Eva Wine 75cl', brand: 'Eva', category: 'Wine', packSize: 'Carton (12 bottles)' },
  { name: '4th Street Sweet Red 75cl', brand: '4th Street', category: 'Wine', packSize: 'Carton (12 bottles)' },
  { name: '4th Street Sweet White 75cl', brand: '4th Street', category: 'Wine', packSize: 'Carton (12 bottles)' },

  // ─── CREAM LIQUEUR / LOCAL SPIRITS ────────────────────────
  { name: 'Amarula Cream 75cl', brand: 'Amarula', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Chelsea Dry Gin 75cl', brand: 'Chelsea', category: 'Spirit', packSize: 'Carton (12 bottles)' },
  { name: 'Chelsea London Dry Gin 35cl', brand: 'Chelsea', category: 'Spirit', packSize: 'Carton (24 bottles)' },
  { name: 'Action Bitters 20cl', brand: 'Action Bitters', category: 'Spirit', packSize: 'Carton (24 bottles)' },
  { name: 'Alomo Bitters 20cl', brand: 'Alomo', category: 'Spirit', packSize: 'Carton (24 bottles)' },
  { name: 'Alomo Bitters 75cl', brand: 'Alomo', category: 'Spirit', packSize: 'Carton (12 bottles)' },

  // ─── SACHET / POUCH DRINKS ────────────────────────────────
  { name: 'Capri-Sonne Orange 20cl', brand: 'Capri-Sonne', category: 'Juice', packSize: 'Pack (40 pouches)' },
  { name: 'Bigi Premium Water 50cl Sachet', brand: 'Bigi', category: 'Water', packSize: 'Bag (20 sachets)' },
];

export const libraryCategories = [
  'All', 'Soft Drink', 'Beer', 'Stout', 'Malt', 'Energy', 'Water', 'Juice', 'Spirit', 'Wine',
];
